<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="A procedural macro that exposes internal errors to external errors the consuming applications should handle. It requires that the internal error implements [`error_support::ErrorHandling`]."><title>handle_error in logins - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-46f98efaafac5295.ttf.woff2,FiraSans-Regular-018c141bf0843ffd.woff2,FiraSans-Medium-8f9a781e4970d388.woff2,SourceCodePro-Regular-562dcc5011b6de7d.ttf.woff2,SourceCodePro-Semibold-d899c5a5c4aeb14a.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2" crossorigin href="../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../static.files/normalize-76eba96aa4d2e634.css"><link rel="stylesheet" href="../static.files/rustdoc-081576b923113409.css"><meta name="rustdoc-vars" data-root-path="../" data-static-root-path="../static.files/" data-current-crate="logins" data-themes="" data-resource-suffix="" data-rustdoc-version="1.79.0 (129f3b996 2024-06-10)" data-channel="1.79.0" data-search-js="search-bf21c90c8c1d92b1.js" data-settings-js="settings-4313503d2e1961c2.js" ><script src="../static.files/storage-e32f0c247825364d.js"></script><script defer src="sidebar-items.js"></script><script defer src="../static.files/main-20a3ad099b048cf2.js"></script><noscript><link rel="stylesheet" href="../static.files/noscript-09095024cf37855e.css"></noscript><link rel="alternate icon" type="image/png" href="../static.files/favicon-32x32-422f7d1d52889060.png"><link rel="icon" type="image/svg+xml" href="../static.files/favicon-2c020d218678b618.svg"></head><body class="rustdoc attr"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button></nav><nav class="sidebar"><div class="sidebar-crate"><h2><a href="../logins/index.html">logins</a><span class="version">0.1.0</span></h2></div><div class="sidebar-elems"></div></nav><div class="sidebar-resizer"></div><main><div class="width-limiter"><nav class="sub"><form class="search-form"><span></span><div id="sidebar-button" tabindex="-1"><a href="../logins/all.html" title="show sidebar"></a></div><input class="search-input" name="search" aria-label="Run search in the documentation" autocomplete="off" spellcheck="false" placeholder="Type ‘S’ or ‘/’ to search, ‘?’ for more options…" type="search"><div id="help-button" tabindex="-1"><a href="../help.html" title="help">?</a></div><div id="settings-menu" tabindex="-1"><a href="../settings.html" title="settings">Settings</a></div></form></nav><section id="main-content" class="content"><div class="main-heading"><h1>Attribute Macro <a href="index.html">logins</a>::<wbr><a class="attr" href="#">handle_error</a><button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><span class="out-of-band"><a class="src" href="../src/error_support_macros/lib.rs.html#63">source</a> · <button id="toggle-all-docs" title="collapse all docs">[<span>&#x2212;</span>]</button></span></div><pre class="rust item-decl"><code>#[handle_error]</code></pre><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><p>A procedural macro that exposes internal errors to external errors the
consuming applications should handle. It requires that the internal error
implements [<code>error_support::ErrorHandling</code>].</p>
<p>Additionally, this procedural macro has side effects, including:</p>
<ul>
<li>It would log the error based on a pre-defined log level. The log level is defined
in the [<code>error_support::ErrorHandling</code>] implementation.</li>
<li>It would report some errors using an external error reporter, in practice, this
is implemented using Sentry in the app.</li>
</ul>
<h2 id="example"><a class="doc-anchor" href="#example">§</a>Example</h2>
<div class="example-wrap ignore"><a href="#" class="tooltip" title="This example is not tested">ⓘ</a><pre class="rust rust-example-rendered"><code><span class="kw">use </span>error_support::{handle_error, GetErrorHandling, ErrorHandling};
<span class="kw">use </span>std::fmt::Display
<span class="attr">#[derive(Debug, thiserror::Error)]
</span><span class="kw">struct </span>Error {}
<span class="kw">type </span><span class="prelude-ty">Result</span>&lt;T, E = Error&gt; = std::result::Result&lt;T, E&gt;;
<span class="kw">impl </span>Display <span class="kw">for </span>Error {
    <span class="kw">fn </span>fmt(<span class="kw-2">&amp;</span><span class="self">self</span>, f: <span class="kw-2">&amp;mut </span>std::fmt::Formatter&lt;<span class="lifetime">'_</span>&gt;) -&gt; std::fmt::Result {
        <span class="macro">write!</span>(f, <span class="string">"Internal Error!"</span>)
    }
}

<span class="attr">#[derive(Debug, thiserror::Error)]
</span><span class="kw">struct </span>ExternalError {}

<span class="kw">impl </span>Display <span class="kw">for </span>ExternalError {
    <span class="kw">fn </span>fmt(<span class="kw-2">&amp;</span><span class="self">self</span>, f: <span class="kw-2">&amp;mut </span>std::fmt::Formatter&lt;<span class="lifetime">'_</span>&gt;) -&gt; std::fmt::Result {
        <span class="macro">write!</span>(f, <span class="string">"External Error!"</span>)
    }
}

<span class="kw">impl </span>GetErrorHandling <span class="kw">for </span>Error {
   <span class="kw">type </span>ExternalError = ExternalError;

   <span class="kw">fn </span>get_error_handling(<span class="kw-2">&amp;</span><span class="self">self</span>) -&gt; ErrorHandling&lt;<span class="self">Self</span>::ExternalError&gt; {
       ErrorHandling::convert(ExternalError {})
   }
}

<span class="comment">// The `handle_error` macro maps from the error supplied in the mandatory argument
// (ie, `Error` in this example) to the error returned by the function (`ExternalError`
// in this example)
</span><span class="attr">#[handle_error(Error)]
</span><span class="kw">fn </span>do_something() -&gt; std::result::Result&lt;String, ExternalError&gt; {
   <span class="prelude-val">Err</span>(Error{})
}

<span class="comment">// The error here is an `ExternalError`
</span><span class="kw">let _</span>: ExternalError = do_something().unwrap_err();</code></pre></div>
</div></details></section></div></main></body></html>